name: "M-A-P Daily Paper"
title: null
markdown: GFM
# Google Analytics
google_analytics: G-JVCDSQLJ0Y
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - archived_papers.md
  - archived_papers
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links