name: "M-A-P Daily Paper"
title: null
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - archived_papers.md
  - archived_papers
# Google Analytics
google_analytics: G-V41B4J3KF4